In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score

In [28]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [5]:
from sklearn.datasets import load_breast_cancer

In [15]:
data = load_breast_cancer()

In [19]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [17]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [53]:
X = pd.DataFrame(data= data.data, columns=data.feature_names)

In [54]:
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  radius error  texture error  perimeter error  \
0                 0.07871        1.0950         0.9053            8.589   
1                 0.05667        0.5435         0.7339            3.398   
2                 0.05999        0.7456         0.7869            4.585   
3                 0.09744        0.4956         1.1560            3.445   
4                 0.05883        0.7572         0.7813            5.438   

   area error  smoothness error  compactness error  concavity error  \
0      153.40          0.006399            0.04904          0.05373   
1       74.08          0.005225            0.01308          0.01860   
2       94.03          0.006150            0.04006          0.03832   
3       27.23          0.009110            0.07458          0.05661   
4       94.44          0.011490            0.02461          0.05688   

   concave points error  symmetry error  fractal dimension error  \
0               0.01587         0.03003                 0.006193   
1               0.01340         0.01389                 0.003532   
2               0.02058         0.02250                 0.004571   
3               0.01867         0.05963                 0.009208   
4               0.01885         0.01756                 0.005115   

   worst radius  worst texture  worst perimeter  worst area  worst smoothness  \
0         25.38          17.33           184.60      2019.0            0.1622   
1         24.99          23.41           158.80      1956.0            0.1238   
2         23.57          25.53           152.50      1709.0            0.1444   
3         14.91          26.50            98.87       567.7            0.2098   
4         22.54          16.67           152.20      1575.0            0.1374   

   worst compactness  worst concavity  worst concave points  worst symmetry  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   worst fractal dimension  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678

In [55]:
y = data.target

In [66]:
#train test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [67]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

# Feature selection by feature importance of random forest classifier

In [68]:
sel = SelectFromModel(RandomForestClassifier(n_estimators = 100 , random_state = 0 , n_jobs= -1 ))

In [69]:
sel.fit(X_train,y_train)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                                 class_weight=None,
                                                 criterion='gini',
                                                 max_depth=None,
                                                 max_features='auto',
                                                 max_leaf_nodes=None,
                                                 max_samples=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=100, n_jobs=-1,
                                                 oob_score=False,
 

In [70]:
sel.get_support()

array([ True, False,  True,  True, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False,  True,  True, False, False, False,
        True, False, False])

In [71]:
len(sel.get_support())

30

In [72]:
X_train.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='object')

In [73]:
features = X_train.columns[sel.get_support()]
features

Index(['mean radius', 'mean perimeter', 'mean area', 'mean concavity',
       'mean concave points', 'area error', 'worst radius', 'worst perimeter',
       'worst area', 'worst concave points'],
      dtype='object')

In [74]:
len(features)

10

In [65]:
#how it select 9 feature by using mean of all

np.mean(sel.estimator_.feature_importances_)

0.03333333333333333

In [75]:
sel.estimator_.feature_importances_

array([0.03699612, 0.01561296, 0.06016409, 0.0371452 , 0.0063401 ,
       0.00965994, 0.0798662 , 0.08669071, 0.00474992, 0.00417092,
       0.02407355, 0.00548033, 0.01254423, 0.03880038, 0.00379521,
       0.00435162, 0.00452503, 0.00556905, 0.00610635, 0.00528878,
       0.09556258, 0.01859305, 0.17205401, 0.05065305, 0.00943096,
       0.01565491, 0.02443166, 0.14202709, 0.00964898, 0.01001304])

In [ ]:
# we select features having mean = 0.33 

In [76]:
X_train_rfc = sel.transform(X_train)
X_test_rfc = sel.transform(X_test)

In [77]:
X_train_rfc.shape , X_test_rfc.shape

((455, 10), (114, 10))

In [47]:
def run_randomForest(X_train, X_test, y_train, y_test):
    clf = RandomForestClassifier(n_estimators= 100, random_state= 0, 
                                 n_jobs= -1)
    clf.fit(X_train , y_train)
    y_pred = clf.predict(X_test)
    print('Accuracy:' , accuracy_score(y_test , y_pred))

# On rfc dataset

In [79]:
%%time
run_randomForest(X_train_rfc, X_test_rfc, y_train, y_test)

Accuracy: 0.9473684210526315
Wall time: 492 ms


# On Original dataset

In [80]:
%%time
run_randomForest(X_train, X_test, y_train, y_test)

Accuracy: 0.9649122807017544
Wall time: 496 ms


# Recurssive feature elimination

In [82]:
from sklearn.feature_selection import RFE

In [83]:
sel = RFE(RandomForestClassifier(n_estimators = 100 , random_state = 100 , n_jobs= -1 ), n_features_to_select= 15)

In [84]:
sel.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                     class_weight=None, criterion='gini',
                                     max_depth=None, max_features='auto',
                                     max_leaf_nodes=None, max_samples=None,
                                     min_impurity_decrease=0.0,
                                     min_impurity_split=None,
                                     min_samples_leaf=1, min_samples_split=2,
                                     min_weight_fraction_leaf=0.0,
                                     n_estimators=100, n_jobs=-1,
                                     oob_score=False, random_state=100,
                                     verbose=0, warm_start=False),
    n_features_to_select=15, step=1, verbose=0)

In [87]:
sel.get_support()

array([False,  True,  True,  True, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False])

In [86]:
Features = X_train.columns[sel.get_support()]
Features

Index(['mean texture', 'mean perimeter', 'mean area', 'mean concavity',
       'mean concave points', 'area error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry'],
      dtype='object')

In [88]:
len(Features)

15

In [92]:
#RFE

X_train_rfe = sel.transform(X_train)
X_test_rfe = sel.transform(X_test)

In [93]:
X_train_rfc.shape, X_test_rfc.shape

((455, 15), (114, 15))

In [94]:
%%time
run_randomForest(X_train_rfe, X_test_rfe, y_train, y_test)

Accuracy: 0.9824561403508771
Wall time: 499 ms


In [95]:
%%time
run_randomForest(X_train, X_test, y_train, y_test)

Accuracy: 0.9649122807017544
Wall time: 539 ms


# 3) Feature selection by Gradient Boost Tree Importance

In [96]:
from sklearn.ensemble import GradientBoostingClassifier

In [102]:
sel = RFE(GradientBoostingClassifier(n_estimators = 100 , random_state = 0 ),
          n_features_to_select= 12)

In [103]:
sel.fit(X_train, y_train)

RFE(estimator=GradientBoostingClassifier(ccp_alpha=0.0,
                                         criterion='friedman_mse', init=None,
                                         learning_rate=0.1, loss='deviance',
                                         max_depth=3, max_features=None,
                                         max_leaf_nodes=None,
                                         min_impurity_decrease=0.0,
                                         min_impurity_split=None,
                                         min_samples_leaf=1,
                                         min_samples_split=2,
                                         min_weight_fraction_leaf=0.0,
                                         n_estimators=100,
                                         n_iter_no_change=None,
                                         presort='deprecated', random_state=0,
                                         subsample=1.0, tol=0.0001,
                                         validation_frac

In [105]:
sel.get_support()

array([False,  True, False, False,  True, False, False,  True,  True,
       False, False, False, False,  True, False, False,  True, False,
       False, False,  True,  True,  True,  True, False, False,  True,
        True, False, False])

In [106]:
Features = X_train.columns[sel.get_support()]
Features

Index(['mean texture', 'mean smoothness', 'mean concave points',
       'mean symmetry', 'area error', 'concavity error', 'worst radius',
       'worst texture', 'worst perimeter', 'worst area', 'worst concavity',
       'worst concave points'],
      dtype='object')

In [107]:
len(Features)

12

In [110]:
X_train_rfe = sel.transform(X_train)
X_test_rfe = sel.transform(X_test)

In [112]:
X_train_rfe.shape, X_test_rfe.shape

((455, 12), (114, 12))

In [113]:
%%time
run_randomForest(X_train_rfe, X_test_rfe, y_train, y_test)

Accuracy: 0.9736842105263158
Wall time: 482 ms


In [114]:
%%time
run_randomForest(X_train, X_test, y_train, y_test)

Accuracy: 0.9649122807017544
Wall time: 505 ms


In [ ]:
# for loop to see each feature accuracy 

In [115]:
for index in range(1,31):
    sel = RFE(GradientBoostingClassifier(n_estimators = 100 , random_state = 0 ),
          n_features_to_select= index)
    sel.fit(X_train, y_train)
    X_train_rfe = sel.transform(X_train)
    X_test_rfe = sel.transform(X_test)
    print('Selected Features', index)
    run_randomForest(X_train_rfe, X_test_rfe, y_train, y_test)
    print()

Selected Features 1
Accuracy: 0.8771929824561403

Selected Features 2
Accuracy: 0.9035087719298246

Selected Features 3
Accuracy: 0.9649122807017544

Selected Features 4
Accuracy: 0.9736842105263158

Selected Features 5
Accuracy: 0.9649122807017544

Selected Features 6
Accuracy: 0.9912280701754386

Selected Features 7
Accuracy: 0.9736842105263158

Selected Features 8
Accuracy: 0.9649122807017544

Selected Features 9
Accuracy: 0.9736842105263158

Selected Features 10
Accuracy: 0.956140350877193

Selected Features 11
Accuracy: 0.956140350877193

Selected Features 12
Accuracy: 0.9736842105263158

Selected Features 13
Accuracy: 0.956140350877193

Selected Features 14
Accuracy: 0.956140350877193

Selected Features 15
Accuracy: 0.9649122807017544

Selected Features 16
Accuracy: 0.956140350877193

Selected Features 17
Accuracy: 0.9649122807017544

Selected Features 18
Accuracy: 0.9473684210526315

Selected Features 19
Accuracy: 0.9649122807017544

Selected Features 20
Accuracy: 0.947368421052

In [ ]:
# here 1st 6 features gives almost 99% accuracy then why to select all 30 features

# so lets know which feature are they 

In [119]:
#for index in range(1,31):
sel = RFE(GradientBoostingClassifier(n_estimators = 100 , random_state = 0 ),
      n_features_to_select= 6)
sel.fit(X_train, y_train)
X_train_rfe = sel.transform(X_train)
X_test_rfe = sel.transform(X_test)
print('Selected Features', 6)
run_randomForest(X_train_rfe, X_test_rfe, y_train, y_test)
print()

Selected Features 6
Accuracy: 0.9912280701754386



In [121]:
features = X_train.columns[sel.get_support()]
features

Index(['mean concave points', 'area error', 'worst texture', 'worst perimeter',
       'worst area', 'worst concave points'],
      dtype='object')

In [ ]:
# In above we use Gradient boost to select feature and done classification using 
#  randomForestclassifier

In [ ]:
#Now in both casses we use randomForest

In [122]:
for index in range(1,31):
    sel = RFE(RandomForestClassifier(n_estimators = 100 , random_state = 0, n_jobs=-1 ),
          n_features_to_select= index)
    sel.fit(X_train, y_train)
    X_train_rfe = sel.transform(X_train)
    X_test_rfe = sel.transform(X_test)
    print('Selected Features', index)
    run_randomForest(X_train_rfe, X_test_rfe, y_train, y_test)
    print()

Selected Features 1
Accuracy: 0.8947368421052632

Selected Features 2
Accuracy: 0.9298245614035088

Selected Features 3
Accuracy: 0.9473684210526315

Selected Features 4
Accuracy: 0.9649122807017544

Selected Features 5
Accuracy: 0.9649122807017544

Selected Features 6
Accuracy: 0.956140350877193

Selected Features 7
Accuracy: 0.956140350877193

Selected Features 8
Accuracy: 0.9649122807017544

Selected Features 9
Accuracy: 0.9736842105263158

Selected Features 10
Accuracy: 0.9736842105263158

Selected Features 11
Accuracy: 0.9649122807017544

Selected Features 12
Accuracy: 0.9736842105263158

Selected Features 13
Accuracy: 0.9649122807017544

Selected Features 14
Accuracy: 0.9736842105263158

Selected Features 15
Accuracy: 0.9736842105263158

Selected Features 16
Accuracy: 0.9736842105263158

Selected Features 17
Accuracy: 0.9824561403508771

Selected Features 18
Accuracy: 0.9649122807017544

Selected Features 19
Accuracy: 0.9649122807017544

Selected Features 20
Accuracy: 0.973684210

In [ ]:
# Here at 17 features we get accuracy of 98% and then it decreasing from then 
#  so why  to select feature after 17 
#  select 17 feature and buil model